### ISSUE TITLE
Choking on `f(::Int...)`

### ISSUE THREAD

**Issue by thofma** [MilesCranmer/DispatchDoctor.jl#16]
Trying it out with a large package I found
```
julia> @stable f(::Int...) = 2
ERROR: syntax: invalid "::" syntax around /bla/DispatchDoctor/uWnHi/src/DispatchDoctor.jl:306
```

**Comment by MilesCranmer** [comment]
Thanks, looks like another edge case I need to add. In the meantime you can do f(::Vararg{Int}) and it should hopefully work.

**Comment by MilesCranmer** [comment]
Looks like this line: https://github.com/MilesCranmer/DispatchDoctor.jl/blob/532ebcb39d509d859e784357c1dc13ac95e7fe1a/src/DispatchDoctor.jl#L247 is not injecting the symbol here. It normally should do a `gensym` if any arg does not have a symbol.

**Comment by MilesCranmer** [comment]
Fixed:

```julia
julia> @stable f(::Int...) = 2
f (generic function with 1 method)

julia> f(1, 2)
2
```

Send more if you find 'em!
