### ISSUE TITLE
Ignore union splitting?

### ISSUE THREAD

**Issue by ChrisRackauckas** [MilesCranmer/DispatchDoctor.jl#29]
Since union splitting optimized code is a bit different from a full type instability, it would probably make sense to have a way to ignore that. That would fix the iterate case and remove the special casing there.

**Comment by MilesCranmer** [comment]
I think you might be able to set this globally with:

```julia
import DispatchDoctor as DD

DD.type_instability(::Type{<:Union}) = false
```

Locally, though, we would need a new parameter.

**Comment by MilesCranmer** [comment]
Let me know if #31 is good and I can merge...
