### ISSUE TITLE
Mark the stability checks as non differentiable?

### ISSUE THREAD

**Issue by avik-pal** [MilesCranmer/DispatchDoctor.jl#32]
See https://buildkite.com/julialang/luxcore-dot-jl/builds/88#018ff4e6-b8ea-4fee-9c5b-8759bfdb35ab/316-4214

Introducing `@stable` in https://github.com/LuxDL/LuxCore.jl/pull/28 makes the code non-differentiable.

We should probably mark the checking code block as CRC non_differentiable. Not sure what happens with Enzyme

**Comment by MilesCranmer** [comment]
With Enzyme it seems to work — I have an integration test for it: https://github.com/MilesCranmer/DispatchDoctor.jl/blob/02b46f6060c84c632dedf5e602dd3ca6a2c72d95/test/enzyme.jl#L17

What’s the right way to hide the instability check from other AD backends? And also why doesn’t it work out of the box? It’s not returning anything different so I am surprised.

**Comment by avik-pal** [comment]
Something like [`ChainRulesCore.@ignore_derivatives()`](https://juliadiff.org/ChainRulesCore.jl/stable/api.html#ChainRulesCore.@ignore_derivatives)

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by MilesCranmer** [comment]
Hm, interesting. I wonder if this should be patched here, or within CRC? It seems like you would always want it to skip `@warn`

**Comment by avik-pal** [comment]
Oh wait, I see it is purely generated by Logging.

But I am not entirely sure how to patch this in CRC because the generated code has `try ... catch` and doesn't really call into a function that has `try ... catch`

cc @oxinabox if you have any thoughts on whether this can be done in CRC

**Comment by MilesCranmer** [comment]
Here's a MWE without DispatchDoctor; just the warning:

```julia
julia> function f(x)
           if false
               @warn "$(typeof(x))"
           end
           x
       end
f (generic function with 1 method)

julia> Zygote.gradient(f, 0.5)
ERROR: Compiling Tuple{typeof(f), Float64}: try/catch is not supported.
Refer to the Zygote documentation for fixes.
https://fluxml.ai/Zygote.jl/latest/limitations
```

**Comment by MilesCranmer** [comment]
https://github.com/FluxML/Zygote.jl/issues/269 🙂

**Comment by MilesCranmer** [comment]
Okay seeing that that hasn't been fixed for nearly 5 years, I'll just patch here. Will make a PR soon.
