### ISSUE TITLE
`@generated` functions lead to world age problems

### ISSUE THREAD

**Issue by matthias314** [MilesCranmer/DispatchDoctor.jl#6]
I have the impression that DispatchDoctor has problems with `@generated` functions. At present, I don't have anything close to an MWE. Nevertheless, I want to point out that this problem exists.

Here are the steps to reproduce it: Check out the branch `dispatchdoctor-worldage` of https://github.com/matthias314/SmallCollections.jl . Go to the `src` directory, start Julia and say:
```
julia> include("SmallCollections.jl")
Main.SmallCollections

julia> using .SmallCollections

julia> v = SmallVector{8,Int8}(1:3)
3-element SmallVector{8, Int8}:
 1
 2
 3

julia> fasthash(v)
ERROR: MethodError: no method matching bitsize(::Type{Int8})
The applicable method may be too new: running in world age 31520, while current world is 31833.
```
I believe the culprit is the `@generated` function `bits` starting at line 127 in staticvectors.jl . Needless to say, without DispatchDoctor is works.

**Comment by MilesCranmer** [comment]
i suppose `@stable` should skip `@generated`? 

It should also skip `@capture` (MacroTools), `@model` (Turing) since they have custom syntax within functions.

**Comment by MilesCranmer** [comment]
Btw to test your hypothesis you should use `@unstable` on any blocks of code to turn it off.
