### ISSUE TITLE
Might need `EnzymeRules.inactive` in addition to `ChainRulesCore.@non_differentiable`

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/DispatchDoctor.jl#60]
Context: `EnzymeRules.inactive` does not import the `ChainRulesCore.@non_differentiable` rules from https://github.com/MilesCranmer/DispatchDoctor.jl/blob/50faa812aec95da232467af4e03d82e28ca408bf/ext/DispatchDoctorChainRulesCoreExt.jl#L13-L26

While this isn't necessarily problematic by itself, and doesn't interact with the derivatives at all, it seems that sometimes Enzyme.jl wants the variables to be `Duplicated()` when using DispatchDoctor.jl, whereas without, they can be `Const()`. (I think this only happens if LLVM is unable to remove the type instability check during optimization passes? But not sure)

My guess is that this is because the DispatchDoctor warning messages prints out information about the variables, so Enzyme thinks that it needs them?

Example: The test https://github.com/MilesCranmer/SymbolicRegression.jl/blob/0f14c5f7255803fe4cd9bb085142afe9cc245ad7/test/test_expression_derivatives.jl#L140 results in the following error (I convert it to a warning as I haven't been able to debug it) –

```
 Mismatched activity for:   store i32 %.fca.6.extract, i32 addrspace(10)* %.innerparm1.sroa.11.0..sroa_cast, align 8, !dbg !18, !alias.scope !27, !noalias !31 const val:   %.fca.6.extract = extractvalue { {} addrspace(10)*, {} addrspace(10)*, { i8, {} addrspace(10)*, {} addrspace(10)*, i64, i64 }, i64, float, float, i32, i8, i8, float, i64, i64, i8, i8, i8, i8, {} addrspace(10)*, i64, float, i8, i8, i64, {} addrspace(10)*, float, float, i8, i8, double, i64, i64, float, float, i64, i64, i8, i64, i8, float, i64, i64, i64, i8, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, i8, i8, i64, i8, {} addrspace(10)*, float, i64, {} addrspace(10)*, {} addrspace(10)*, float, {} addrspace(10)*, i64, i8, i64, i8, i8, {} addrspace(10)*, i8, i8, i8 } %2, 6, !dbg !9
│         value=Unknown object of type Union{Nothing, Float32}
│         llvalue=  %.fca.6.extract = extractvalue { {} addrspace(10)*, {} addrspace(10)*, { i8, {} addrspace(10)*, {} addrspace(10)*, i64, i64 }, i64, float, float, i32, i8, i8, float, i64, i64, i8, i8, i8, i8, {} addrspace(10)*, i64, float, i8, i8, i64, {} addrspace(10)*, float, float, i8, i8, double, i64, i64, float, float, i64, i64, i8, i64, i8, float, i64, i64, i64, i8, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, i8, i8, i64, i8, {} addrspace(10)*, float, i64, {} addrspace(10)*, {} addrspace(10)*, float, {} addrspace(10)*, i64, i8, i64, i8, i8, {} addrspace(10)*, i8, i8, i8 } %2, 6, !dbg !9
│        You may be using a constant variable as temporary storage for active memory (https://enzyme.mit.edu/julia/stable/faq/#Activity-of-temporary-storage). If not, please open an issue, and either rewrite this variable to not be conditionally active or use Enzyme.API.runtimeActivity!(true) as a workaround for now
│        
│        Stacktrace:
│         [1] ##eval_loss_simulator#819
│           @ ~/PermaDocuments/SymbolicRegressionMonorepo/SymbolicRegression.jl/src/LossFunctions.jl:105
```

Though the value in question here I don't think should cause such an issue. 

The potential line its referencing is here: https://github.com/MilesCranmer/SymbolicRegression.jl/blob/cd23a6e25c64d00565c3ae3905d06dc3c63033ed/src/LossFunctions.jl#L225. I don't think this should interact with the gradients at all so I'm not sure why it's hit an error. Note that it's not an issue when DispatchDoctor.jl is turned off.

cc @avik-pal @wsmoses

**Comment by wsmoses** [comment]
Correct, EnzymeRules.inactive is very similar, but semantically distinct from chainrules.nondifferentiable.

In particular `EnzymeRules.inactive` says that both the operation does not do any differentiable updates, and any values created by it could never contain differentiable data [e.g. it is illegal to mark Vector{Float64}(undef, 2) as inactive, since in the future the returned value justifiably could contain differentiable data].

**Comment by wsmoses** [comment]
And yeah here you now have a type-unstable `Union{Nothing, Float32}` object which comes from guaranteed inactive memory, that you're storing somewhere which could have an active use.

**Comment by MilesCranmer** [comment]
Cool, thanks, I'll make an Enzyme extension to complement the ChainRulesCore one.

> And yeah here you now have a type-unstable `Union{Nothing, Float32}` object which comes from guaranteed inactive memory, that you're storing somewhere which could have an active use.

Just to clarify – this term is basically just a constant term defined in the user-specified options that gets added to the loss (which is then differentiated). So, should it be declared in `Duplicated()`? I was thinking of also simply making a closure function with that term inside it to avoid the extra copy.
